language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

install: 
  # C++14
  - sudo add-apt-repository -y ppa:beineri/opt-qt593-trusty
  - sudo apt-get -qy update
  - sudo apt-get install -qq g++-6 gcc-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  # Qt5
  - sudo apt-get install -qq qt59-meta-minimal
  - export QMAKE=/opt/qt59/bin/qmake

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "sh -e ./update_repository.sh"
  - gcc --version
  - g++ --version
  # Not using qmake because it's from Qt 4 in the default Travis instance
  - $QMAKE -v

script: 
  - $QMAKE -r
  - make -j
  - ./bin/release/x64/FileCommander