version: '{build}'
init:
  clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      qt: 5.10.1\msvc2017_64
      VS_VERSION: 2017
      BUILD_ARCH: x64    
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      qt: 5.9\msvc2015
      VS_VERSION: 2015
      BUILD_ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      qt: 5.9\msvc2015_64
      VS_VERSION: 2015
      BUILD_ARCH: x64

configuration:
  - Release

install:
- git submodule update --init --recursive --depth 1
- set PATH=C:\Qt\%qt%\bin;%PATH%;
- IF "%VS_VERSION%" == "2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r)
- IF "%VS_VERSION%" == "2015" (IF "%BUILD_ARCH%" == "x64" (call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r) ELSE (call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r))
- cd file-commander-core\core-tests\
- IF "%VS_VERSION%" == "2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r)
- IF "%VS_VERSION%" == "2015" (IF "%BUILD_ARCH%" == "x64" (call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r) ELSE (call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r))
- cd ..\..\

build_script:
 - msbuild file-commander.sln /t:Build /p:Configuration=Release
 - cd file-commander-core\core-tests\
 - msbuild /t:Build /p:Configuration=Release
 - cd ..\..\

after_build:
 - .\bin\release\%BUILD_ARCH%\FileCommander.exe --test-launch

test_script:
 - .\bin\release\%BUILD_ARCH%\fso_test.exe -s -r junit -o fso_test.xml
 - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\fso_test.xml))

 - .\bin\release\%BUILD_ARCH%\fso_test_high_level.exe -s -r junit -o fso_test_high_level.xml
 - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\fso_test_high_level.xml))

 - ps: |
     For ($i=1; $i -le 10; $i++) {
       $randomSeed = ((get-date -Uformat %s).remove(10, 1));
       $randomSeed = $randomSeed.substring($randomSeed.Length - 8);
       & .\bin\release\$($env:BUILD_ARCH)\operationperformer_test.exe -s -r junit -o operationperformer_test_$i.xml --std-seed $randomSeed;
       (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\operationperformer_test_$i.xml));
     }