version: 1.0.{build}
environment:
  matrix:
    - qt: 5.7\msvc2013
    - qt: 5.7\msvc2013_64
    - qt: 5.7\msvc2015
    - qt: 5.7\msvc2015_64
install:
- git submodule update --init --recursive 
- set PATH=%PATH%;C:\Qt\%qt%\bin; 
- qmake.exe -tp vc -r
build:
  project: file-commander.sln #required to avoid .smproj-induced build error
  parallel: true
  verbosity: minimal