version: '{build}'
init:
  clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      qt: 5.15\msvc2019_64
      VS_VERSION: 2019
      WIN_SDK: 10.0.18362.0
      BUILD_ARCH: x64

configuration:
  - Release

install:
- git submodule update --init --recursive --depth 5
- dir "C:\Program Files (x86)\Windows Kits\10\include\"
- pushd file-commander-core\core-tests\
- call "%programfiles(x86)%\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 %WIN_SDK% && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r
- popd
- set QTDIR32="C:\Qt\5.15\msvc2019"
- set QTDIR64="C:\Qt\%qt%"

build_script:
 - pushd installer\windows\
 - create_installer.bat
 - popd

 - pushd file-commander-core\core-tests\
 - msbuild /t:Build /p:Configuration=Release;PlatformToolset=v141
 - popd

after_build:
 - .\bin\release\%BUILD_ARCH%\FileCommander.exe --test-launch

test_script:
 - .\bin\release\%BUILD_ARCH%\fso_test.exe -s -r junit -o fso_test.xml
 - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\fso_test.xml))

 - .\bin\release\%BUILD_ARCH%\fso_test_high_level.exe -s -r junit -o fso_test_high_level.xml
 - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\fso_test_high_level.xml))

 - ps: |
     For ($i=1; $i -le 20; $i++) {
       $randomSeed = ((get-date -Uformat %s).remove(10, 1));
       $randomSeed = $randomSeed.substring($randomSeed.Length - 8);
       & .\bin\release\$($env:BUILD_ARCH)\operationperformer_test.exe -s -r junit -o operationperformer_test_$i.xml --std-seed $randomSeed;
       (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\operationperformer_test_$i.xml));
     }

 - ps: |
    $randomSeed = ((get-date -Uformat %s).remove(10, 1));
    $randomSeed = $randomSeed.substring($randomSeed.Length - 8);
    & .\bin\release\$($env:BUILD_ARCH)\filecomparator_test.exe -s -r junit -o filecomparator_test.xml --std-seed $randomSeed;
    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/", (Resolve-Path .\filecomparator_test.xml));

deploy:
  description: $($env:APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: E8CRx0r0qADoE0JR3QUFwD0bQSRGSUerCeCJs4BU6B+Rmz9BMvRLZmbtrqpPzGVS
  artifact: .\installer\windows\FileCommander.exe
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
