version: 1.0.{build}
install:
- git submodule update --init --recursive 
- set PATH=%PATH%;C:\Qt\5.7\msvc2013\bin; 
- qmake.exe -tp vc -r
build:
  project: file-commander.sln #required to avoid .smproj-induced build error
  parallel: true
  verbosity: minimal