version: 1.0.{build}
init:
  clone_depth: 1
environment:
  matrix:
    - qt: 5.8\msvc2015
    - qt: 5.8\msvc2015_64
install:
- git submodule update --init --recursive --depth 1
- set PATH=%PATH%;C:\Qt\%qt%\bin; 
- qmake.exe -tp vc -r
build:
  project: file-commander.sln #required to avoid .smproj-induced build error
  parallel: true
  verbosity: minimal